name: Build and Deploy to dockerhub

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest

      steps:
        # Step 1: Check out the code
        - name: Checkout Code
          uses: actions/checkout@v3
        
        # Step 2: Log in to Docker Hub
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step 3: Build and Push Docker image
        - name: Build and Push Docker image
          uses: docker/build-push-action@v6
          with:
              context: .
              file: ./docker/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/express-test:test2  # Replace with your Docker Hub username and repository
        
        # Step 4: Verify Pushed Image
        - name: Verify Pushed Image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/express-test:test2  # Replace with your Docker Hub username and repository
    
    deploy:
      name: Deploy to EC2
      needs: build-and-push  # Run only after the build-and-push job
      runs-on: ubuntu-latest

      steps:
        # Step 1: Deploy to EC2
        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              script: |
                sudo docker pull ${{ secrets.DOCKER_USERNAME }}/express-test:test2
                sudo docker stop express-test-app || true
                sudo docker rm express-test-app || true
                sudo docker run --name express-test-app -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/express-test:test2